### ISSUE TITLE
help

### ISSUE THREAD

**Issue by 20246688** [ModernOctave/XTDrone-Notes#1]
[ERROR] [1727331187.845439, 2111.633000]: bad callback: <bound method Communication.cmd_vel_flu_callback of <main.Communication object at 0x7f6c2a317fd0>>
Traceback (most recent call last):
File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
cb(msg)
File "multirotor_communication.py", line 114, in cmd_vel_flu_callback
self.hover_state_transition(msg.linear.x, msg.linear.y, msg.linear.z, msg.angular.z)
File "multirotor_communication.py", line 148, in hover_state_transition
self.hover()
File "multirotor_communication.py", line 197, in hover
self.target_motion = self.construct_target(x=self.current_position.x,y=self.current_position.y,z=self.current_position.z,yaw=self.current_yaw)
AttributeError: 'NoneType' object has no attribute 'x'

**Comment by 20246688** [comment]
原因：当前用户没有权限写入 rosdep 的缓存文件。
解决办法：sudo chown -R $USER:$USER /home/jy/.ros
建议：打开debug更容易定位奇奇怪怪的问题。
